# Site settings
title: Aaron Anthony
description: 'Business Card Page'
url: 'http://thomas.zuehlke.family'
baseurl: ''
profilepic: '/images/aaron.jpg'
bkimage: '/images/Spherical_Wave_C60.png'
google_analytics: UA-XXXXXX-X
font_awesome: '1b735903d0.js'  #FIXME can't use the same code on two sites

author:
  name: 'Aaron Anthony'
  email: aaron@sphericalwave.com
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  sphericalwave
#  linkedin_username:  thomas-zühlke-889182165
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
